[build]
  publish = "_site"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@quarto/netlify-plugin-quarto"
```

Then create a file called **`runtime.txt`** in your repository root with this content:
```
3.6