[build]
  publish = "_site"  # Quarto output folder
  command = "quarto render"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@quarto/netlify-plugin-quarto" 

[build.image]
  name = "ubuntu-jammy"
