---
title: "Teaching"
lang: en
execute:
  echo: false
comments: false
toc: false
---

## Teaching Goal
My primary teaching goal is to empower students to think critically, apply knowledge with confidence, and take ownership of their learning journey. I aim to make my teaching materials accessible, relevant, and engaging.  Ultimately, I want my students to leave the classroom not only with stronger technical skills but also with greater confidence in their ability to learn, solve real-world problems, and grow as independent thinkers and economists.

## Brief Teaching Philosophy Statement
I view teaching as a form of service, and my role is to support students as they grow into confident, curious, and independent economists. I do this by building a classroom environment where students feel seen, heard, and respected. I design clear, flexible materials to make challenging content accessible, and I regularly seek feedback to adjust my teaching in real time. I hold high expectations while providing consistent support, so students are both challenged and encouraged. Through reflection, responsiveness, and care, I meet students where they are and help them move forward.

## Independent Instructor

- AGEC 516 – Mathematical tools for Agricultural and Applied Economics, Fall 2024, Purdue  
  - Evaluation: 4.67/5  
  - [Syllabus](content/pdfs/AGEC516_Fall2024_Syllabus_YiWang.pdf)

- Ph.D. Math Camp, Summer 2024, Purdue

## Teaching Assistant

- Graduate Courses  
  - AGEC 516 – Mathematical tools for Agricultural and Applied Economics, Fall 2022, Fall 2023, Purdue

- Undergraduate Courses  
  - ARE 106 – Econometric Theory & Applications, Spring 2020, University of California, Davis


## Teaching Scholarship
#### 2024 AAEA First Annual Teaching Academy Workshop, New Orleans, LA
- I attended this one-day AAEA workshop focused on effective teaching, classroom engagement, and inclusive learning. Sessions on building community and classroom engagement helped shape my teaching philosophy and informed my approach to designing and teaching my first master’s-level course, which received positive student feedback and led to my nomination for Purdue’s College of Agriculture Graduate Student Excellence in Teaching Award. The workshop also enriched my teaching “knowledge tank”—a growing foundation of strategies and insights I continually draw from as I evolve in my teaching journey.

#### Professional Development through Teaching Academy Webinars, September 2024 - May 2025
- Since September 2024, I have actively participated in monthly Teaching Academy webinars, which continue to enrich my teaching practices. I’ve provided the opportunity to explore strategies to make classrooms more welcoming and interactive, including the use of LTIs and a case-study approach to connect theory with real-world problems. Each session adds to the toolkit I draw from to support my overarching goal: helping students become confident, engaged, and application-oriented agricultural economists.

#### Practical Applications of Generative AI in Teaching and Learning, Purdue University Online Workshops, Fall 2024

- This workshop series shifted my perspective on AI in the classroom—from concern to curiosity and integration. I learned practical strategies for using generative AI to enhance student engagement, accessibility, and instructional efficiency. I now view AI as an add-on that, when used thoughtfully, can enrich the overall learning experience.

